# This GitHub action builds the React app for production.
name: CD-Frontend-Firebase
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_and_deploy:
    name: Prepare & Deploy App
    runs-on: ubuntu-18.04
    steps:
      - name: Get source code
        uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1
      - name: Get Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Configure cache for future deployments
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install npm packages
        run: npm install
      - name: Build app
        run: npm run build
#      - name: Provide Google Credentials
#        uses: google-github-actions/setup-gcloud@master
#        with:
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          export_default_credentials: true
#      - name: Send to Google Cloud Storage
#        uses: weslenng/gcp-storage-sync@master
#        with:
#          args: -d
#        env:
#          GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SA_KEY }}
#          GCP_STORAGE_BUCKET: ${{ secrets.GCP_BUCKET_NAME }}
#          SOURCE_DIR: "build"
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POLY_DOCS }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
